# system
mode: 0
distribute: False
num_parallel_workers: 4
val_while_train: True

# dataset
dataset: 'imagenet'
data_dir: 'path/to/imagenet/'
shuffle: True
dataset_download: False
batch_size: 64
drop_remainder: True
train_split: val/
val_split: val/

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
auto_augment: 'randaug-m9-mstd0.5-inc1'
interpolation: bicubic
re_prob: 0.25
re_value: 'random'
cutmix: 1.0
mixup: 0.8
mixup_prob: 1.0
mixup_mode: batch
mixup_off_epoch: 0
switch_prob: 0.5
crop_pct: 0.875
color_jitter: 0.3

# model
model: 'deit_base'
num_classes: 1000
pretrained: False
ckpt_path: ''

keep_checkpoint_max: 10
ckpt_save_dir: './ckpt'

epoch_size : 300
dataset_sink_mode: True
amp_level: O2
ema: False
ema_decay: 0.99996
clip_grad: False
clip_value: 5.0

# loss
loss: 'CE'
label_smoothing: 0.1

# lr scheduler
lr_scheduler: 'cosine_decay'
min_lr: 1.0e-5
lr: 0.0005
warmup_epochs: 5
warmup_factor: 0.002
decay_epochs: 30
decay_rate: 0.1

# optimizer
opt: 'adamw'
filter_bias_and_bn: True
eps: 1.0e-8
momentum: 0.9
weight_decay: 0.05
dynamic_loss_scale: True
use_nesterov: False
