# system
mode: 0
distribute: False
num_parallel_workers: 4
val_while_train: True

# dataset
dataset: 'imagenet'
data_dir: 'path/to/imagenet/'
shuffle: True
dataset_download: False
batch_size: 32
drop_remainder: True
val_split: val

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
auto_augment: 'randaug-m9-mstd0.5-inc1'
interpolation: bilinear
re_prob: 0.25
re_value: 'random'
cutmix: 0.5
mixup: 0.5
mixup_prob: 1.0
mixup_mode: batch
mixup_off_epoch: 0.0
switch_prob: 0.5
crop_pct: 0.96

# model
model: 'convmixer_1536_20'
num_classes: 1000
pretrained: False
ckpt_path: ''

keep_checkpoint_max: 10
ckpt_save_dir: './ckpt'

epoch_size: 300
dataset_sink_mode: True
amp_level: 'O0'
use_ema: False
ema_decay: 0.9999
use_clip_grad: True
clip_value: 1.0

# loss
loss: 'CE'
label_smoothing: 0.1

# lr scheduler
lr_scheduler: 'cosine_decay'
lr: 0.001
warmup_epochs: 0
warmup_factor: 0.007
min_lr: 0.0001
decay_epochs: 300

# optimizer
opt: 'adamw'
momentum: 0.9
weight_decay: 0.0001
loss_scale: 1024
dynamic_loss_scale: False
