# Copyright 2022 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

#system config
enable_modelarts: True
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True

# dataset config
dataset: 'imagenet'
data_dir: './imagenet/'
shuffle: True
dataset_download: False
batch_size: 320
drop_remainder: True

# Augmentation config
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
vflip: 0.
interpolation: 'bicubic'
auto_augment: randaug-m9-mstd0.5-inc1
re_prob: 0.25
mixup: 0.8
cutmix: 1.0
color_jitter: 0.4
crop_pct: 0.935
ema: True

# model config
model: 'crossvit15'
num_classes: 1000
pretrained: False
ckpt_path: ''
keep_checkpoint_max: 30
ckpt_save_dir: './ckpt/'
epoch_size: 600
dataset_sink_mode: True
amp_level: 'O3'
drop_path_rate: 0.1

# loss config
loss: 'CE'
label_smoothing: 0.1

# lr scheduler config
scheduler: 'warmup_cosine_decay'
lr: 0.0009
min_lr: 0.00001
warmup_epochs: 30
decay_epochs: 270
decay_rate: 0.1
num_cycles: 2
cycle_decay: 1


# optimizer config
opt: 'adamw'
weight_decay: 0.05
filter_bias_and_bn: True
loss_scale: 512
use_nesterov: False
eps: 1e-8


# Scheduler parameters
lr_epoch_stair: True



