# system
mode: 0
distribute: False
num_parallel_workers: 2
val_while_train: True

# dataset
dataset: 'imagenet'
data_dir: 'path/to/imagenet/'
shuffle: True
dataset_download: False
batch_size: 32
drop_remainder: True
val_split: val
train_split: val

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
auto_augment: 'randaug-m9-mstd0.5-inc1'
interpolation: bicubic
re_prob: 0.24
re_value: 'random'
cutmix: 1.0
mixup: 0.8
mixup_prob: 1.0
mixup_mode: 'batch'
mixup_off_epoch: 0.0
switch_prob: 0.5
crop_pct: 0.9

# model
model: 'alt_gvt_small'
num_classes: 1000
pretrained: False
ckpt_path: ''

keep_checkpoint_max: 10
ckpt_save_dir: './ckpt'

epoch_size: 300
dataset_sink_mode: True
amp_level: 'O0'
ema: False
clip_grad: True
clip_value: 5.0
drop_rate: 0.0
drop_path_rate: 0.1

# loss
loss: 'CE'
label_smoothing: 0.5

# lr scheduler
lr_scheduler: 'cosine_decay'
warmup_epochs: 20
lr: 0.0001
warmup_factor: 0.001
min_lr: 0.00001

# optimizer
opt: 'adamw'
eps: 1e-8
weight_decay: 0.05
dynamic_loss_scale: True
