# system config
mode: 0
distribute: True
num_parallel_workers: 16
val_while_train: True

# dataset config
dataset: 'imagenet'
data_dir: '/cache/dataset/imagenet/imagenet/'
shuffle: True
dataset_download: False
batch_size: 128
drop_remainder: True

# Augmentation config
image_resize: 224
hflip: 0.5
color_jitter: 0.4
interpolation: 'bicubic'
crop_pct: 0.875
re_prob: 0.25
mixup: 0.8
cutmix: 1.0
auto_augment: 'randaug-m9-mstd0.5-inc1'
use_ema: True
ema_decay: 0.99996

# model config
model: 'xcit_tiny_12_p16'
num_classes: 1000
pretrained: False
ckpt_path: ""
keep_checkpoint_max: 30
save_checkpoint: True
ckpt_save_dir: './xcit_tiny_12_p16'
epoch_size: 500
dataset_sink_mode: True
amp_level: 'O2'
drop_rate: 0.0
drop_path_rate: 0.0

# loss config
loss: 'CE'
label_smoothing: 0.1

# lr scheduler config
scheduler: 'warmup_cosine_decay'
min_lr: 0.00001
lr: 0.0005
warmup_epochs: 40
decay_epochs: 460
decay_rate: 0.1

# optimizer config
opt: 'adamw'
filter_bias_and_bn: True
weight_decay: 0.05
loss_scale: 1024
use_nesterov: False
